version: '2'

services: 
#####################
  database:
    image: mysql:latest
    environment:
      - "MYSQL_DATABASE=eduction"
      - "MYSQL_ROOT_PASSWORD=rootroot"
    ports:
        - "3306:3306"
    healthcheck:
      test: "exit 0"
#####################
  redis:
    image: redis:6.2.1
#####################
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-server
    ports:
     - "4000:4000"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started